services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9091:80
    environment:
      DOTNET_ENVIRONMENT: "Production"
      DOTNET_ConnectionStrings__SqlDatabase: "Server=db;Database=sportstore;User ID=sa;Password=Administrator123!;"
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Administrator123!"
    ports:
      - "1433:1433"
