version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DOTNET_ENVIRONMENT: "Production"
      DOTNET_ConnectionStrings__SqlDatabase: "Server=db,1433;Database=sporthal;User Id=sa;Password=Administrator123!;"

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Administrator123!"
    ports:
      - "1433:1433"
